pipeline {
    agent any
    tools {
        nodejs 'nodejs:22.4.0'  // Define Node.js tool with the specified version
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Install dependencies') {
            steps {
                sh 'npm install'
            }
        }
        stage('Build') {
            steps {
                sh 'npm run build'
            }
        }
        stage('Test') {
            steps {
                sh 'npm test'
            }
        }
        stage('Build Image') {
            steps {
                sh 'docker build -t cicd_demo:latest .'
            }
        }
    }
}
