pipeline{
    agent {
        docker{
            image 'node:20.15.0-alpine3.20'
        }
    }
    stages{
        // checkout source code
        stage("Checkout"){
            steps{
                checkout scm
            }
        }
        // install deps
        stage("Install dependencies"){
            steps{
                sh 'npm install'
            }
        }
        // build the app (linting,etc)
        stage("Build"){
            steps{
                sh 'npm run build'
            }
        }
        // run unit tests
        stage("Test"){
            steps{
                sh 'npm test'
            }
        }
        // build docker image
        stage("Build Image"){
            steps{
                sh 'docker build -t cicd_demo:latest .'
            }
        }
    }
}